version: '3'
services:
  grafana:
    image: grafana/grafana:7.0.3
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/etc/grafana
  prometheus:
    image: prom/prometheus:v2.18.1
    volumes:
      - ./prometheus:/etc/prometheus
    command: "--config.file=\"/etc/prometheus/prometheus.yaml\" --web.enable-lifecycle"
    ports:
      - 9090:9090
  alertmanager:
    image: prom/alertmanager:v0.20.0
    volumes:
      - ./alertmanager:/etc/alertmanager
    command: "--config.file=/etc/alertmanager/config.yaml"
    ports:
      - 9093:9093
  node-exporter-1:
    image: prom/node-exporter:v1.0.0
  node-exporter-2:
    image: prom/node-exporter:v1.0.0
  node-exporter-3:
    image: prom/node-exporter:v1.0.0
  redis:
    image: redis:6
  redis-exporter:
    image: oliver006/redis_exporter:v1.6.1-alpine
    environment:
      REDIS_ADDR: redis://redis:6379
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/data:/var/lib/mysql
  mysql-exporter:
    image: prom/mysqld-exporter:v0.12.1
    environment:
      DATA_SOURCE_NAME: "root:root@(mysql:3306)/"

