global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 10s

rule_files:
  - /etc/prometheus/rules/*.yaml

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
      - targets:
        - alertmanager:9093

scrape_configs:
  - job_name: 'main'
    static_configs:
      - targets:
        - prometheus:9090
        - node-exporter-1:9100
        - node-exporter-2:9100
        - node-exporter-3:9100
        - redis-exporter:9121
        - mysql-exporter:9104
